spring:
  application:
    name: spring-security-with-jwt
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/springsecurityjwt
    username: root
    password: 1234

server:
  error:
    include-message: always