
--- ROLES ---

INSERT INTO role(name) SELECT * FROM (SELECT 'ROLE_ADMIN') AS tmp WHERE NOT EXISTS (SELECT name FROM role WHERE name = 'ROLE_ADMIN') LIMIT 1;
INSERT INTO role(name) SELECT * FROM (SELECT 'ROLE_USER') AS tmp WHERE NOT EXISTS (SELECT name FROM role WHERE name = 'ROLE_USER') LIMIT 1;